---
title: "Where is the Time?"
author: "Zoe Worrall"
date: "9/16/24"
categories: true
---

### So about Time

I've been running low on sleep recently, and its not for lack of trying. I have a reason for it -- mainly being that there just aren't enough hours in the day to do all the schoolwork I need to do. Forget socialization, or not feeling like doing things -- I'm doing so much all the time and it still doesn't cut down the massive tidal wave hurtling towards me.

I think that school is, generally, like a tsunami -- at least that's how I've explained it to people. You see the signs of it coming long before it does, and dealing with it is a terrible time. Specifically, it's like facing off against a tsunami with a small little bucket, and you're told by the captain "you got it buddy, I believe in you" -- in my case, the captain is my past self who put me in this situation.

So how do we deal with the stress of it all? How do we work towards still succeeding while trying to do everything? Some may say that you should take a break -- I think that's perfectly valid. I actually love throwing myself into work, but I find that I tend to procrastinate on some work by doing others. I recommend, then, that everyone gets a way to track their time and how much time they're spending for any one thing, whether its to distribute classwork better or whether its to actually see your friends every Saturday.

Here are some solutions I've found; feel free to try them in your own time:

* Set up a set time that you'll meet with your friend, and make sure you tell them its time limited

* When you do a silent study session with a friend, bring something to read; if you're doing something that requires complex math problems, for example, you may need help or start making exclamations that will take away from work.

* Use Toggl Tap! I found this recently through MicroP's, and its quite useful for budgeting my time and making sure I'm not procrastinating too much on any one thing.