---
title: "The World of Epic the Musical"
description: "How community makes success"
author: "Zoe Worrall"
date: "10/22/24"
categories:
  - blogpost
---

### The World of Epic the Musical

I think one of the greatest things that's come out of the internet is the ability to avoid major coorporations, and really find something human in a sea of extreme corporate safety. Take a look at modern Marvel movies, for example; if there was one thing to notice from these movies, its that the most recnt movies have become stale and sad because they rely too much on what they know will work: big bad guy, the heroes save the day, normally with some catchy one liners. They lack the characterization of earlier movies, and that is in part because they are so successful that they no longer feel the need to take risks - and this comes at the cost of the community that will support the movies in the future.

There isn't a community for movies like "Wish" (Disney). There isn't a community for movies like "Thor: Love and Thunder", and I think that there's a lot of hatred and ambiguity around the Star Wars Sequels. Ignoring the fact that the common thread here is Disney, what is more interesting is that often times the failing grace of the movies isn't the cost or the spectacle, but the characterizations and the chances/risks taken. I think nothing stands as more of an example of how this goes over with audiences than the 200 million sunk cost into Sony's "Concord" FPS game, which was taken off of the game store basically a week after its launch because no one was playing it (think 700 players online, in an industry where the norm is to have tens of thousands of players). Why? Because there was nothing new about the game, in an extremely oversaturated market (I'll leave some really good youtube videos below talking about why Concord failed so spectacularly).

This was a preface for why I think "Epic: The Musical" is so good. It's a musical about the Odyssey. Is it accurate to the Odyssey? Not really. It isn't able to recontextualize a lot of the historical context that played into the story - for example, it can't carry across the weight of the cyclops' killing of the men being so, so bad by Greek standards, because we don't understand in modern day that back during the times when the Odyssey was prominant, guests were ALWAYS given gifts or some sort of welcome (i.e., the cyclops represents a lack of refinement, humanity, and honor that we simply can't contextualize with a modern lens). But that's not important, what IS important is that it took the risk to begin with of adapting material as complex and fun as the Odyssey. And it does it with CHARACTER.

This character is what allows a community to foster, and nowhere do we see that more than in the artist community. Artists like Wolfy the Witch, Tamatama, gigi, and more (all on Youtube) make animatics (story boards for animations, basically) have created a backdrop for the insane work and catchy songs written for a purely CONCEPTUAL musical. This isn't going to be on Broadway, and it doesn't have to be. It's something being made, purely for fun, that's created a growing community of artists online. And you don't need to chose just one interpretation as "canonical" for the animatics, you can chose your own adventure. Similar to the SCP Foundation, for example, this is an entirely fan-made project for something that is entirely fan-made. In the modern day, when so many major studios and organizations are dependent on nostalgia or past products, its so refreshing to see something new; something that is able to bring together communities, rather than drive them into the ground.

Epic the Musical is a modern epic, in many ways; it is a way of passing along a story, in a new form albeit, but it has reached so many more people in this way than it ever would have if it had stayed as a poem. I really encourage anyone who wants to understand what WILL succeed in modern day to take a look at communities like the one for Jorge Rivera-Herrans' work, because the passion and drive behind a project, in the end, is what makes the project good; rather than driven by money or success, you should be driven by making a story that you care about. Passion will always lead to success - and that's what we should really keep in mind.

Youtube Recommendations:

Concord:

* [Concord Died for a Reason](https://www.youtube.com/watch?v=20xjQKrdmz0&t=242s&pp=ygUMY29uY29yZCBmYWls)

* [Pro Character Designer Breaks Down, Fixes Concord Character Designs](https://www.youtube.com/watch?v=fHiddBwE394&t=1174s&pp=ygUMY29uY29yZCBmYWls)

* [Death of a Game: Concord](https://www.youtube.com/watch?v=iLEUuvlsT_4&t=1547s&pp=ygUMY29uY29yZCBmYWls)

* [Concord: The Biggest Failure in Gaming](https://www.youtube.com/watch?app=desktop&v=llTHKy4iFAw)


Epic the Musical Animatic Recommendations

* [The Horse and the Infant & Just a Man, gigi](https://www.youtube.com/watch?v=QXeYVV1zcUc&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Ruthlessness, Tamatama](https://www.youtube.com/watch?v=grTNCeQa6Bs&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Ruthlessness, AnniFlama](https://www.youtube.com/watch?v=0IsYf_0UGLE&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Ruthlessness, gigi](https://www.youtube.com/watch?v=skVSbITX4kY)

* [Scylla, gigi](https://www.youtube.com/watch?v=aPxjbWbhyPc&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Love in Paradise, Duvetbox](https://www.youtube.com/watch?v=lpVWEq_wIrs&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Suffering, gigi](https://www.youtube.com/watch?v=h84fYAsvsco&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Suffering, Duvetbox](https://www.youtube.com/watch?v=3Vo0KbqRB5k&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [God Games, AnniFlama](https://www.youtube.com/watch?v=r8zSNdgCJhU&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [God Games, SixofClovers](https://www.youtube.com/watch?v=75LFI4QTEQk&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [God Games, Mumda](https://www.youtube.com/watch?v=JYWIIE6p4yY&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Legendary, Rochi](https://www.youtube.com/watch?v=CWFBiM_LZwI&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [Little Wolf, Duvetbox](https://www.youtube.com/watch?v=BPiJF7rceiA&t=108s&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)

* [We'll be Fine, gigi](https://www.youtube.com/watch?v=DR26QjyF__g&pp=ygUZZXBpYyB0aGUgbXVzaWNhbCBhbmltYXRpYw%3D%3D)
