---
title: "Let's Discuss: What's up with True Crime?"
author: "Zoe Worrall"
date: "11/3/24"
categories:
  - blogpost
---

### The Rabbithole

I tend to find that I get the most work done while I'm alone. I also tend to get most distracted while I'm with people, or while I'm listening to any music that is either 1. new or 2. has English in it. That means that although I tend to do best while listening to something in the background, and you'd be hard pressed to find me without earbuds in, I'm often either listening to kpop or true crime.

K-pop is extremely popular now - no question why I'm listening to that.

But what about true crime? I've had this discussion with many people before but it just seems so odd of a fixation for us to have. My mom fell down the rabbit hole, my sister did too, as did my aunt and I believe even my maternal grandmother at one point. There's something about women and true crime that just clicks, and it's resulted in a massive (and sometime exploitative) market for true crime.

So let's think about that - why does true crime find such an audience with women, and why do we continue to buy into it?

I think one of the primary things is that its both interesting and "helpful", at least to our squirrel brains. None of us want to be harmed, and so hearing about how we best avoid falling into the same traps, or seeing how often times our instincts about people and our fear is valid, is particularly helpful.

I looked up statistics for this, and get this - according to the Council for Criminal Justice, ["Females report that they make up a larger share of violent crime victims: 51% of all violent victimizations in 2022 compared to 41% of all victimizations in 1993, the start of the data series. (This figure is drawn from the National Crime Victimization Survey; it excludes homicides and includes simple assaults."](https://counciloncj.org/criminal-justice-gaps-between-women-and-men-narrow-on-violence-other-key-meaures/#:~:text=Females%20report%20that%20they%20make,start%20of%20the%20data%20series.). I think that generally, not only have we become more aware of how dangerous the world is for us, but we are more able to take action because we have the information at our fingertips; we can protect ourselves long before anything dangerous happens with the help of technology.

So true crime in part is popular with women because we are scared of getting hurt.

I'd argue that another reason it's popular is because it proves our preconceived notions right. Everyone loves to hate, loves to feel superior. And there is no time to feel more superior than when we hate on `scumbags`, people who have hurt others and have finally gotten their comeuppance. The amount of times that I go into a comments section and see "Oh I can see how much of a fool he was for thinking he could get away with this" or "She is truly the most despicable human, I could never be like that". That is to say that we compare ourselves all the time with true crime, and so I think that true crime, in part, necessitates a bit of an ego boost for an individual.

There's a reason why beauty vlogging mixed with true crime has taken off (Look at Bailey Sarian - a Youtuber who talks true crime while putting on makeup); we want to feel casual, to feel like we're put together and safe while also seeing how terrible it could be without that safety.
It may just also be a way to push us to fix the world, to change it for the better.

Either way, the weird duality of women and true crime (which often depicts violence against women) is something that I'm sure will be in many psychology theses or ideations in the future. It just remains to be seen what everyone's final takeaway is.