project:
  preview:
    port: 5029
  type: website

website:
  title: "Zoe Worrall's Website"
  image: images/ZoeWorrall_Photo.png
  favicon: images/bg_test.png
  open-graph: true
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    logo: images/zoe_logo.png
    title: false
    collapse-below: lg
    left:
      - href: projects/e-155_website/blog.qmd
      - text: "E155 Labs"
        menu:
        - href: projects/e-155_website/labs/lab1/lab1.qmd
        - href: projects/e-155_website/labs/lab2/lab2.qmd
        - href: projects/e-155_website/labs/lab3/lab3.qmd
        - href: projects/e-155_website/labs/lab4/lab4.qmd
        - href: projects/e-155_website/labs/lab5/lab5.qmd
        - href: projects/e-155_website/labs/lab6/lab6.qmd
        - href: projects/e-155_website/labs/lab7/lab7.qmd
      - text: "Projects"
        menu: 
        - text: "E155 Project"
          href: projects/e-155_website
        - href: projects/E80_sub.qmd
        - href: projects/mcf_lci.qmd
        - href: projects/open_ivis.qmd
      - href: art/index.qmd
      - href: contacts/index.qmd

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    left: |
      Copyright
    center:
      - icon: github
        href: https://github.com/zoe-worrall
      - icon: linkedin
        href: https://www.linkedin.com/in/zoeworrall
    right: |


format:
  html:
    # theme: [cosmos, zoe_text.scss]
    theme: jolla
    font-family: "Times New Roman"
    # css: zoe_text.css
    toc: true
    smooth-scroll: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto  # basically ensures that R, Python, and Julia code is only executed locally
