---
title: "About"
---

## Welcome

Mae g'ovannen! My name is Zoe Worrall, and I am currently a senior Engineering Major at Harvey Mudd College. Although I have experience with a broad range of engineering topics including materials engineering, continuum mechanics, and manufacturing, my primary interests lie in signal processing, radio frequency, and optical systems. 

## Engineering

Mudd's general Engineering gives its students a strong background in a variety of subjects, but by far what has clicked with me the most in my schooling has been electrical engineering, especially through research.

Whether it was working under PI Dr. Jason Gallicchio on software defined radio, or within the Harvey Mudd Biophotonics Lab with Dr. Joshua Brake, I've learned to work with electromagnetic waves, their generation, and their processing. 

My favorite courses at HMC have included E&M, Data Structures for C++, Digital Design and Computer Architecture, analog circuit design, and Systems Engineering.


## Art

In addition to majoring in Engineering, I am also pursuing a concentration in Studio Art. 