website:
  title: "MicrorProcessors"
  image: images/img_test.png
  favicon: images/bg_test.png
  open-graph: true
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    logo: images/img_test.png
    logo-alt: "Test Image"
    title: false
    collapse-below: lg
    left:
      - href: blog.qmd
      - href: labs/lab1/lab1.qmd

  page-navigation: true

  back-to-top-navigation: false

  page-footer:
    background: "#000000"
    left: |
      Copyright
    center:
      - icon: github
        href: https://github.com/zoe-worrall
    right: |


format:
  html:
    theme: [lux, zoe_text.scss]
    css: zoe_text.css
    toc: true
    smooth-scroll: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 250px

execute: 
  freeze: auto  # basically ensures that R, Python, and Julia code is only executed locally